### ISSUE TITLE
Use Silaeder instead of Silaedr

### ISSUE THREAD

**Issue by pavtiger** [justUlik/justUlik#2]
As I heard from @kolayne, a long time ago he and @OlgaStarunova were applying for a conference and agreed that the _official_ name of the school is `Silaeder`. 
As for me, I totally agree with them and think that **Silaeder** just looks far better than **Silaedr**. So I suggest correcting the school name in your README file.

**Comment by kolayne** [comment]
Hey there! True, although official Russian name is СилаэДР, in English it is officially spelled as SilaeDER. The only exception I know about is the group in VKontacte: its address is incorrect, but it has been so for a long time, so there are now links to that incorrect URL from external resources, so it's not possible to correct the mistake now

**Comment by justUlik** [comment]
Thanks
